---
#  _____                 _     _____                                 _ 
# |  ___|   __ _   ___  | |_  |_   _|  _ __    __ _  __   __   ___  | |
# | |_     / _` | / __| | __|   | |   | '__|  / _` | \ \ / /  / _ \ | |
# |  _|   | (_| | \__ \ | |_    | |   | |    | (_| |  \ V /  |  __/ | |
# |_|      \__,_| |___/  \__|   |_|   |_|     \__,_|   \_/    \___| |_|
#
Um die Umstellung zu erleichtern, müssen Sie
Name  : FastTravel
Autor :   Ad5001
description: Travel in MCPE faster and easier than you ever tought !
website: http://github.com/Ad5001/FastTravel
Version   : 2.0
API   : [ 2.0.0 , 3.0.0-ALPHA1 , 3.0.0-ALPHA2 , 3.0.0-ALPHA3 2
main: Ad5001\FastTravel\Main
commands: []
permissions: []
...
